---
- name: print some thing in hte console
  hosts: backend
  become: yes
  gather_facts: yes

  tasks:
    - name: print some thing
      debug:
        msg: "hello welcome all "


#---
#- name: print something in the console
#  hosts: backend
#  become: yes
#  gather_facts: yes

#  tasks:
    - name: print something
      debug:
        msg: "hello welcome all 2"
