-name: install and run the nginx in the child node 
 host: web
 become: yes 
 tasks:
  name: ping the server
  ansible.builtin.dnf:
    name: nginx
    state: install
  name: start and enable the service 
  ansible.builtin.service:
    name: nginx
    state: started
    enable: yes 

  