- name: install and run the nginx in the child node
  hosts: web
  become: yes
  tasks:
  - name: Install nginx rpm from a local file
    ansible.builtin.dnf:
      name: nginx
      state: present
  - name: start and enable the services
    ansible.builtin.service:
      name: hnginx
      state: stopped
      enabled: yes
