- name: arguments  from the user prompt
  hosts: localhost
  vars_prompt:
  
   - name: USERNAME
     prompt: Please enter the user name 
     private: false
    
   - name: PASSWORD
     vars_prompt: Please enter password
     private: true      


  tasks:
    - name: prompt vaiables
      ansible.builtin.debug:
      msg: "username is {{USERNAME}} And password is {{PASSWORD}}"
