- name: arguments  from the user prompt
  hosts: localhost
  vars_prompt:
    - name: username
      prompt: What is your username?
      private: false

    - name: password
      prompt: What is your password?
      private: true

  tasks:
    - name: prompt vaiables
      ansible.builtin.debug:
      msg: "username is {{USERNAME}} And password is {{PASSWORD}}"
