- name: arguments  from the user prompt
  hosts: localhost
  vars_prompt:
    - name: USERNAME
      prompt: What is your username?
      private: false

    - name: PASSWORD
      prompt: What is your password?
      private: true
  tasks:
   - name: propt varaibles
     ansible.builtin.debug:
      msg: " user name is {{USERNAME}} and password is {{PASSWORD}}"
