- name: check an user is existed or not 
  hosts: web
  become: yes
  gather_facts: true
  tasks:
    - name: check the user is existed or not 
      ansible.builtin.command: id kedarnath
      ignore_errors: true
      register: USER

    - name: print some thing
      ansible.builtin.debug:
        msg: "hello "  

    - name: print the USER_Register
      ansible.builtin.command:
        msg: "print the user is {{USER}}"
