- name: check an user is existed or not 
  hosts: web
  become: yes
  gather_facts: true
  tasks:
    - name: Do not count this as a failure
      ansible.builtin.command: /bin/false
      regester: USER
      ignore_errors: true

    - name: print the  user
      ansible.builtin.debug:
       msg: "user is {{USER}}"
    - name: get massage
      ansible.builtin.debug:
      msg: "hello welcome "
