- name: check an user is existed or not 
  hosts: web
  become: yes
  gather_facts: true
  tasks:
   - name: check the user is existed or not 
     ansible.builtin.command: id kedarnath 
     
   
   - name: get massage
     ansible.builtin.debug:
      msg: "hello welcome "
